# Generated by Django 4.0.3 on 2022-03-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('pan_no', models.IntegerField(null=True, verbose_name='PAN number')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('phn', models.CharField(max_length=10, null=True, verbose_name='Phone')),
                ('dsp', models.TextField(max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('null', models.TextField(max_length=100, null=True)),
                ('user_name', models.TextField(max_length=100, null=True)),
                ('phone_number', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('null', models.TextField(max_length=100, null=True)),
                ('var1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.dealer')),
                ('var2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplychain.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var5', models.TextField(max_length=100, null=True)),
                ('var6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable 6+', to='supplychain.salesman')),
                ('var7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable 7+', to='supplychain.salesman')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var3', models.TextField(max_length=100, null=True)),
                ('var4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplychain.dealer')),
            ],
        ),
        migrations.AddField(
            model_name='dealer',
            name='crt_usr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplychain.user', verbose_name='Create user'),
        ),
    ]
