# Generated by Django 4.0.3 on 2022-03-08 07:54

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('supplychain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name_plural': 'Dealer'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='salesman',
            options={'verbose_name_plural': 'Salesman'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='var3',
        ),
        migrations.RemoveField(
            model_name='items',
            name='var4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='var5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='var6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='var7',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='null',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='var1',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='var2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='null',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='items',
            name='dsp',
            field=models.CharField(max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='items',
            name='itm_dea',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='item_asso_dealer', to='supplychain.dealer'),
        ),
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.CharField(max_length=100, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], default='In stock', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='iaso_sal',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='items_asso_sales', to='supplychain.items'),
        ),
        migrations.AddField(
            model_name='order',
            name='oaso_sal',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='order_asso_sales', to='supplychain.salesman'),
        ),
        migrations.AddField(
            model_name='order',
            name='quanti',
            field=models.CharField(choices=[('kilo', 'kilo'), ('box', 'box')], max_length=4, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='leftover',
            field=models.CharField(max_length=100, null=True, verbose_name='Remaining order'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='saso_dea',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='sales_asso_dealer', to='supplychain.dealer'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='saso_usr',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='sales_asso_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesman',
            name='total_order',
            field=models.CharField(max_length=100, null=True, verbose_name='Total order'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='total_sales',
            field=models.CharField(max_length=100, null=True, verbose_name='Total sales'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer',
            name='crt_usr',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Create user'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='pan_no',
            field=models.CharField(max_length=15, null=True, verbose_name='PAN number'),
        ),
    ]
