# Generated by Django 4.0.3 on 2022-03-08 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0005_alter_order_quanti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='crt_usr',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Create user'),
        ),
        migrations.AlterField(
            model_name='items',
            name='itm_dea',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_asso_dealer', to='supplychain.dealer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='iaso_sal',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_asso_sales', to='supplychain.items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oaso_sal',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_asso_sales', to='supplychain.salesman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quanti',
            field=models.CharField(choices=[('kilo', 'kilo'), ('box', 'box')], max_length=4, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='saso_dea',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_asso_dealer', to='supplychain.dealer'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='saso_usr',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_asso_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
