# Generated by Django 4.0.3 on 2022-03-08 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0006_alter_dealer_crt_usr_alter_items_itm_dea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itm_dea',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_asso_dealer', to='supplychain.dealer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='iaso_sal',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_asso_sales', to='supplychain.items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oaso_sal',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_asso_sales', to='supplychain.salesman'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quanti',
            field=models.CharField(choices=[('box', 'box'), ('kilo', 'kilo')], max_length=4, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='saso_dea',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_asso_dealer', to='supplychain.dealer'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='saso_usr',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_asso_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
