# Generated by Django 4.0.3 on 2022-03-08 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0010_alter_order_quanti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='crt_usr',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Create user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quanti',
            field=models.CharField(choices=[('box', 'box'), ('kilo', 'kilo')], max_length=4, null=True, verbose_name='Quantity'),
        ),
    ]
