# Generated by Django 4.0.3 on 2022-03-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0021_alter_order_quanti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quanti',
            field=models.CharField(choices=[('kilo', 'kilo'), ('box', 'box')], max_length=4, null=True, verbose_name='Quantity'),
        ),
    ]
