# Generated by Django 4.0.3 on 2022-03-20 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Company's name"),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], default='In stock', max_length=12, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
