# Generated by Django 4.0.3 on 2022-03-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_dealer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shop name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_order', to='Myapp.order', verbose_name='Order')),
                ('Salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_salesman', to='Myapp.salesman', verbose_name='Salesman')),
            ],
        ),
    ]
