# Generated by Django 4.0.3 on 2022-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='additional_contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
