# Generated by Django 4.0.3 on 2022-03-24 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_dealer_additional_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesman',
            name='user',
        ),
        migrations.AlterField(
            model_name='salesman',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, unique=True, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
