# Generated by Django 4.0.3 on 2022-03-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_remove_salesman_user_alter_salesman_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='Myapp.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Quantity'),
        ),
    ]
