# Generated by Django 4.0.3 on 2022-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_remove_dealer_user_alter_item_price_alter_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
