# Generated by Django 4.0.3 on 2022-03-28 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_dealer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Salesman_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
